SELECT * FROM location;

INSERT INTO location (suburb,state,country)
VALUES ('Wanaka','Otago','New Zealand'),
('Wellington City','Wellington','New Zealand'),
('Lower Hutt City','Wellington','New Zealand'),
('Upper Hutt City','Wellington','New Zealand'),
('Porirua City','Wellington','New Zealand'),
('Kapiti Coast','Wellington','New Zealand'),
('Windsor','VIC','Australia'),
('Gordon Dam','TAS','Australia'),
('Brunswick','VIC','Australia'),
('Docklands','VIC','Australia'),
('Kew','VIC','Australia'),
('Lake Taupo','Taupo','New Zealand'),
('Huka Falls','Taupo','New Zealand'),
('Rotorua','Bay of Plenty','New Zealand'),
('Waitomo','Waikato','New Zealand'),
('Footscray','VIC','Australia'),
('Box Hill','VIC','Australia'),
('Rose Bay','NSW','Australia'),
('Penrith','NSW','Australia'),
('Woolacombe','Cornwall','United Kingdom'),
('Bala','Gwynedd','United Kingdom'),
('Tenby','Pembrokeshire','United Kingdom'),
('Hay-on-Wye','Powys','United Kingdom'),
('Tamworth','Staffordshire','United Kingdom'),
('Chesterfield','Derbyshire','United Kingdom'),
('Chelmsley Wood','Solihull','United Kingdom'),
('Lea Marston','West Midlands','United Kingdom'),
('Queens Park','West Midlands','United Kingdom'),
('Birmingham','West Midlands','United Kingdom');